/**
 * Spring Boot REST API
 * Employee Management REST API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */



import { HttpRequest } from '../modules/shared/services/http-request.service';
export class MissionControllerApi extends HttpRequest {

    constructor(api_url) {

      super();

      if (api_url) {
        this.api_url = MySuperApp.back_end_endpoint + api_url;
      } else {
        this.api_url = MySuperApp.back_end_endpoint;
      }
    }

    getBaseUrl() {
      return this.api_url;
    }


    /**
     * getPreviewList
     * @param {module:api/MissionControllerApi~getPreviewListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/MissionPreviewDto>}
     */
    getPreviewList(file) {    
      
      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let handleAs = file ? 'blob' : undefined;

      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;

      var url = this.getBaseUrl() + '/missions/preview';
      return this.gatewayRequest(url, 'GET', null, queryParams, handleAs, formParams);  
    }

    /**
     * patchMissionsPreviews
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit limit
     * @param {Number} opts.missionId missionId
     * @param {Number} opts.offset offset
     * @param {Array.<Number>} opts.questCategoryId questCategoryId
     * @param {module:api/MissionControllerApi~patchMissionsPreviewsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MissionDetailDto}
     */
    patchMissionsPreviews(limit, missionId, offset, questCategoryId, file) {    
      
      let pathParams = {
      };
      let queryParams = {
        'limit': limit,
        'missionId': missionId,
        'offset': offset,
        'questCategoryId': this.buildCollectionParam(questCategoryId, 'multi')
      };
      let headerParams = {
      };
      let formParams = {
      };

      let handleAs = file ? 'blob' : undefined;

      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;

      var url = this.getBaseUrl() + '/missions/detail';
      return this.gatewayRequest(url, 'PATCH', null, queryParams, handleAs, formParams);  
    }


  buildCollectionParam (param, collectionFormat) {
    if (!param) {
      return null;
    }
    switch (collectionFormat) {
      case 'csv':
        return param.join(',');
      case 'ssv':
        return param.join(' ');
      case 'tsv':
        return param.join('\t');
      case 'pipes':
        return param.join('|');
      case 'multi':
        // return the array directly as SuperAgent will handle it as expected
        return param;
      default:
        throw new Error('Unknown collection format: ' + collectionFormat);
    }
  };

}

