/**
 * Spring Boot REST API
 * Employee Management REST API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */



import { HttpRequest } from '../modules/shared/services/http-request.service';
export class SecurityControllerApi extends HttpRequest {

    constructor(api_url) {

      super();

      if (api_url) {
        this.api_url = MySuperApp.back_end_endpoint + api_url;
      } else {
        this.api_url = MySuperApp.back_end_endpoint;
      }
    }

    getBaseUrl() {
      return this.api_url;
    }


    /**
     * createInvitation
     * @param {module:model/InvitationDto} invitationDto invitationDto
     * @param {module:api/SecurityControllerApi~createInvitationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseEntity}
     */
    createInvitation(invitationDto, file) {    
      
      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let handleAs = file ? 'blob' : undefined;

      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;

      var url = this.getBaseUrl() + '/security/invitation';
      return this.gatewayRequest(url, 'POST', invitationDto, queryParams, handleAs, formParams);  
    }

    /**
     * extendLogin
     * @param {module:model/RefreshTokenDto} refreshTokenDto refreshTokenDto
     * @param {module:api/SecurityControllerApi~extendLoginCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AccessTokenDto}
     */
    extendLogin(refreshTokenDto, file) {    
      
      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let handleAs = file ? 'blob' : undefined;

      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;

      var url = this.getBaseUrl() + '/security/login/extend';
      return this.gatewayRequest(url, 'POST', refreshTokenDto, queryParams, handleAs, formParams);  
    }

    /**
     * login
     * @param {module:model/LoginDto} loginDto loginDto
     * @param {module:api/SecurityControllerApi~loginCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AccessTokenDto}
     */
    login(loginDto, file) {    
      
      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let handleAs = file ? 'blob' : undefined;

      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;

      var url = this.getBaseUrl() + '/security/login';
      return this.gatewayRequest(url, 'POST', loginDto, queryParams, handleAs, formParams);  
    }

    /**
     * logout
     * @param {module:api/SecurityControllerApi~logoutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseEntity}
     */
    logout(file) {    
      
      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let handleAs = file ? 'blob' : undefined;

      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;

      var url = this.getBaseUrl() + '/security/logout';
      return this.gatewayRequest(url, 'GET', null, queryParams, handleAs, formParams);  
    }

    /**
     * register
     * @param {module:model/RegistrationDto} registrationDto registrationDto
     * @param {String} token token
     * @param {module:api/SecurityControllerApi~registerCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ResponseEntity}
     */
    register(registerDto, registrationToken, file) {    
      let pathParams = {
        'token': registrationToken
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let handleAs = file ? 'blob' : undefined;

      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;

      var url = this.getBaseUrl() + `/security/registration/${registrationToken}`;
      return this.gatewayRequest(url, 'POST', registerDto, queryParams, handleAs, formParams);  
    }

    /**
     * validateRegistrationToken
     * @param {String} token token
     * @param {module:api/SecurityControllerApi~validateRegistrationTokenCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InvitationDto}
     */
    validateRegistrationToken(token, file) {    
      let pathParams = {
        'token': token
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let handleAs = file ? 'blob' : undefined;

      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;

      var url = this.getBaseUrl() + `/security/registration/${token}/validate`;
      return this.gatewayRequest(url, 'GET', null, queryParams, handleAs, formParams); 
    }


  buildCollectionParam (param, collectionFormat) {
    if (!param) {
      return null;
    }
    switch (collectionFormat) {
      case 'csv':
        return param.join(',');
      case 'ssv':
        return param.join(' ');
      case 'tsv':
        return param.join('\t');
      case 'pipes':
        return param.join('|');
      case 'multi':
        // return the array directly as SuperAgent will handle it as expected
        return param;
      default:
        throw new Error('Unknown collection format: ' + collectionFormat);
    }
  };

}

